# Generated by Django 4.2.7 on 2023-12-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка видео'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
